### PR TITLE
Merge from Dev: Add Face Editor from Rope-next (by @Alucard24) and some other changes

### PR DESCRIPTION
**Pull request by argenspin**

### CODE REVIEW

**Comment by gjnave** [comment]
I hate to tell you but the new updates broke the manual install again. I know you are focusing on the full installer, however I know for at least me its important to be able to manual install.

Following the online manual install directions and using conda-rope.bat

**The select faces folder throws this errror when trying to be set:**
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

**and the "find faces" button pops up an error saying "no faces found" and throws this error:**
*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

****************************************

image

image

**Comment by argenspin** [comment]
You shouldn't be using the Update_Rope.bat if you did a manual installation. You have to update it manually by running git pull, downloading the new models as well as updating the new dependencies. For more support, reach me in this discord group: https://discord.gg/EcdVAFJzqp

**Comment by gjnave** [comment]
Ok i shouldnt have mentioend the update.. i just threw it in as an extra comment. Regardless of that (forget I mentioned that), the other stuff is happening. I've installed it dozens of times in the past so I'm not unawares of the software :D

**Comment by gjnave** [comment]
THese are still issues.. the application is broken re: manual install

**Pull request merged**
