### PR TITLE
Added RCT Color transfer when swapping using DFL Models

### PR DESCRIPTION
**Pull request by argenspin**
* Added DFL RCT color transfer
* Added option to keep only a single DFL model in memory

### CODE REVIEW

**Comment by gjnave** [comment]
The bigger issue is that you're setenv file has broken the manual install. 
First of all the PIP requirements don't include onnxruntine, the condaforge install of cuda is not an actual package ( users need to use -c Nvidia cuda toolkit=11.8 instead), and the most devastating is that when choosing a source folder, the application closes down with a tensor RT error. 
I've been having to send users back to the August 20th checkpoint just before you added the new files

**Comment by argenspin** [comment]
> The bigger issue is that you're setenv file has broken the manual install. First of all the PIP requirements don't include onnxruntine, the condaforge install of cuda is not an actual package ( users need to use -c Nvidia cuda toolkit=11.8 instead), and the most devastating is that when choosing a source folder, the application closes down with a tensor RT error. I've been having to send users back to the August 20th checkpoint just before you added the new files

I have updated the install instructions and requirements.txt, It should work fine now. You should use the Rope_Conda.bat file to start the application if you have done manual installation. In the future, I recommend that you move on to use the Portable Installer as it comes with all the dependencies and contains scripts to easily get all the new updates without any hassle.

**Comment by gjnave** [comment]
awesome thank you for doing that. Apprecaite all the great work more than you can know. One last correction:

numexpr   needs to be added to the requirements.txt

**Comment by argenspin** [comment]
> awesome thank you for doing that. Apprecaite all the great work more than you can know. One last correction:
> 
> numexpr needs to be added to the requirements.txt

its already there

**Pull request merged**
